variable "vault_token" {}
variable "env" {}
variable "subnet_cidr_block" {}
variable "default_vpc_id" {}
variable "default_route_table_id" {}
variable "default_vpc_cidr_block" {}
variable "peer_connection_id" {}
variable "dev_vpc_cidr_block" {}
variable "frontend_subnets" {}
variable "backend_subnets" {}
variable "db_subnets" {}
variable "availability_zone" {}
variable "instance_type" {}
variable "sg_id" {}
variable "public_subnets" {}